use_frameworks!

platform :ios, '10.0'

target 'JUNCollectionView_Example' do
  pod 'JUNCollectionView', :path => '../'

  target 'JUNCollectionView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
